In [1]:
import pandas as pd

In [19]:
results_df=pd.read_csv("../data/raw/results.csv")

results_df

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24855,24861,1042,825,210,20,19,16,16,16,0.0,65,\N,\N,63,16,1:21.460,205.632,11
24856,24862,1042,154,210,8,18,17,17,17,0.0,65,\N,\N,59,17,1:21.664,205.118,11
24857,24863,1042,849,3,6,20,18,18,18,0.0,64,\N,\N,53,19,1:21.859,204.629,12
24858,24864,1042,826,213,26,13,19,19,19,0.0,64,\N,\N,59,8,1:20.449,208.216,12
24859,24865,1042,840,211,18,12,\N,R,20,0.0,51,\N,\N,45,18,1:21.694,205.043,130

In [20]:
results_df.drop(columns=["number","laps","time","milliseconds"],inplace=True)

In [21]:
constructors_df=pd.read_csv("../data/raw/constructors.csv")

In [22]:
constructors_df.drop(columns=["url"],inplace=True)
constructors_df

     constructorId constructorRef                  name nationality
0                1        mclaren               McLaren     British
1                2     bmw_sauber            BMW Sauber      German
2                3       williams              Williams     British
3                4        renault               Renault      French
4                5     toro_rosso            Toro Rosso     Italian
..             ...            ...                   ...         ...
206            209          manor        Manor Marussia     British
207            210           haas          Haas F1 Team    American
208            211   racing_point          Racing Point     British
209            212    alpha_tauri  Scuderia Alpha Tauri     Italian
210            213     alphatauri            AlphaTauri     Italian

[211 rows x 4 columns]

In [23]:
constructors_df.rename(columns={"name":"constructor_name","nationality":"constructor_nationality"},inplace=True)

In [24]:
results_cons_df=results_df.merge(constructors_df,on ="constructorId",how="left")

In [25]:
drivers_df=pd.read_csv("../data/raw/drivers.csv")

In [26]:
drivers_df["driver_name"]=drivers_df["forename"] + " " + drivers_df["surname"]

In [27]:
drivers_df.drop(columns=["url","number"],inplace=True)
drivers_df.rename(columns={"nationality":"driver_nationality"},inplace=True)
drivers_df

,driverId,driverRef,code,forename,surname,dob,driver_nationality,driver_name
0,1,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,Lewis Hamilton
1,2,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German,Nick Heidfeld
2,3,rosberg,ROS,Nico,Rosberg,1985-06-27,German,Nico Rosberg
3,4,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,Fernando Alonso
4,5,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish,Heikki Kovalainen
...,...,...,...,...,...,...,...,...
843,845,sirotkin,SIR,Sergey,Sirotkin,1995-08-27,Russian,Sergey Sirotkin
844,846,norris,NOR,Lando,Norris,1999-11-13,British,Lando Norris
845,847,russell,RUS,George,Russell,1998-02-15,British,George Russell
846,848,albon,ALB,Alexander,Albon,1996-03-23,Thai,Alexander Albon
847,849,latifi,LAT,Nicholas,Latifi,1995-06-29,Canadian,Nicholas Latifi

In [28]:
res_cons_driver_df=results_cons_df.merge(drivers_df,on=["driverId"],how="left")
res_cons_driver_df

,resultId,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,fastestLap,...,constructorRef,constructor_name,constructor_nationality,driverRef,code,forename,surname,dob,driver_nationality,driver_name
0,1,18,1,1,1,1,1,1,10.0,39,...,mclaren,McLaren,British,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,Lewis Hamilton
1,2,18,2,2,5,2,2,2,8.0,41,...,bmw_sauber,BMW Sauber,German,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German,Nick Heidfeld
2,3,18,3,3,7,3,3,3,6.0,41,...,williams,Williams,British,rosberg,ROS,Nico,Rosberg,1985-06-27,German,Nico Rosberg
3,4,18,4,4,11,4,4,4,5.0,58,...,renault,Renault,French,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,Fernando Alonso
4,5,18,5,1,3,5,5,5,4.0,43,...,mclaren,McLaren,British,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish,Heikki Kovalainen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24855,24861,1042,825,210,19,16,16,16,0.0,63,...,haas,Haas F1 Team,American,kevin_magnussen,MAG,Kevin,Magnussen,1992-10-05,Danish,Kevin Magnussen
24856,24862,1042,154,210,18,17,17,17,0.0,59,...,haas,Haas F1 Team,American,grosjean,GRO,Romain,Grosjean,1986-04-17,French,Romain Grosjean
24857,24863,1042,849,3,20,18,18,18,0.0,53,...,williams,Williams,British,latifi,LAT,Nicholas,Latifi,1995-06-29,Canadian,Nicholas Latifi
24858,24864,1042,826,213,13,19,19,19,0.0,59,...,alphatauri,AlphaTauri,Italian,kvyat,KVY,Daniil,Kvyat,1994-04-26,Russian,Daniil Kvyat
24859,24865,1042,840,211,12,\N,R,20,0.0,45,...,racing_point,Racing Point,British,stroll,STR,Lance,Stroll,1998-10-29,Canadian,Lance Stroll

In [29]:
res_cons_driver_df.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'grid', 'position',
       'positionText', 'positionOrder', 'points', 'fastestLap', 'rank',
       'fastestLapTime', 'fastestLapSpeed', 'statusId', 'constructorRef',
       'constructor_name', 'constructor_nationality', 'driverRef', 'code',
       'forename', 'surname', 'dob', 'driver_nationality', 'driver_name'],
      dtype='object')

In [34]:
final_df=res_cons_driver_df[res_cons_driver_df["driverId"].isin([1,20,4,8,3,30,822,18,13,817,830,17,117,22,815,102,14,807,137,95])]

final_df

,resultId,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,fastestLap,...,constructorRef,constructor_name,constructor_nationality,driverRef,code,forename,surname,dob,driver_nationality,driver_name
0,1,18,1,1,1,1,1,1,10.0,39,...,mclaren,McLaren,British,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,Lewis Hamilton
2,3,18,3,3,7,3,3,3,6.0,41,...,williams,Williams,British,rosberg,ROS,Nico,Rosberg,1985-06-27,German,Nico Rosberg
3,4,18,4,4,11,4,4,4,5.0,58,...,renault,Renault,French,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,Fernando Alonso
7,8,18,8,6,15,8,8,8,1.0,20,...,ferrari,Ferrari,Italian,raikkonen,RAI,Kimi,RÃ¤ikkÃ¶nen,1979-10-17,Finnish,Kimi RÃ¤ikkÃ¶nen
12,13,18,13,6,4,\N,R,13,0.0,23,...,ferrari,Ferrari,Italian,massa,MAS,Felipe,Massa,1981-04-25,Brazilian,Felipe Massa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24842,24848,1042,830,9,3,3,3,3,15.0,62,...,red_bull,Red Bull,Austrian,max_verstappen,VER,Max,Verstappen,1997-09-30,Dutch,Max Verstappen
24846,24852,1042,815,211,5,7,7,7,6.0,49,...,racing_point,Racing Point,British,perez,PER,Sergio,PÃ©rez,1990-01-26,Mexican,Sergio PÃ©rez
24848,24854,1042,817,4,10,9,9,9,2.0,61,...,renault,Renault,French,ricciardo,RIC,Daniel,Ricciardo,1989-07-01,Australian,Daniel Ricciardo
24849,24855,1042,20,6,15,10,10,10,1.0,62,...,ferrari,Ferrari,Italian,vettel,VET,Sebastian,Vettel,1987-07-03,German,Sebastian Vettel
24850,24856,1042,8,51,16,11,11,11,0.0,60,...,alfa,Alfa Romeo,Italian,raikkonen,RAI,Kimi,RÃ¤ikkÃ¶nen,1979-10-17,Finnish,Kimi RÃ¤ikkÃ¶nen

In [37]:
final_df.to_csv("../data/Modified/san_key3.csv",header=True,index=False)

## All constructors files into one

In [ ]:
constructors_df=pd.read_csv("../data/raw/constructors.csv")
consrtuctor_results_df=pd.read_csv("../data/raw/constructor_results.csv")
constructor_standings_df=pd.read_csv("../data/raw/constructor_standings.csv")
races_df=pd.read_csv("../data/raw/races.csv")
constructors_df.drop(columns=['url'],inplace=True)

In [ ]:
race_const_df= consrtuctor_results_df.merge(races_df,on='raceId',how='left')

race_const_df.rename(columns={'name':'races_name'},inplace=True)
race_const_df.drop(columns=['url'],inplace=True)

In [ ]:
race_const_df= race_const_df.merge(constructors_df,on='constructorId',how='left')
race_const_df.rename(columns={'name':'constructor_name','nationality':'constructor_nationality'},inplace=True)

In [ ]:
race_const_df.head()

In [ ]:
race_const_df=race_const_df.merge(constructor_standings_df,on=['constructorId','raceId'],how='left')
race_const_df.rename(columns={'points':'constructor_point'},inplace=True)

In [ ]:
race_const_df.info()

In [ ]:
# constructorResults <- left_join(constructorResults, constructors %>% select(-url) %>% rename(name_constructor = name), by='constructorId')

# constructorResults <- left_join(constructorResults, constructorStandings %>% rename(point_constructor = points) %>% select(-X), by=c('constructorId','raceId'))

In [ ]:
new_df=consrtuctor_results_df.merge(constructors_df,on='constructorId', how='left')

In [ ]:
new_df.drop(columns=['status'],inplace=True)

In [ ]:
new_df.rename(columns={'name':'constructor_name','nationality':'constructor_nationality','url':'constructor_url'},inplace=True)
new_df

In [ ]:
constructor_standings_df=pd.read_csv("../data/raw/constructor_standings.csv")
# w=constructor_standings_df.loc[constructor_standings_df['wins']==1].count()
constructor_standings_df

In [ ]:
new_cons_df=constructor_standings_df.merge(new_df,on=['raceId','constructorId'], how='left')
new_cons_df.head(5)

In [ ]:
new_cons_df.info()

In [ ]:
#look up the rows with win==1
cons_no1=new_cons_df.loc[new_cons_df['wins']==1]
cons_no1_new=cons_no1[['wins','name']]

In [ ]:
#group the winners by their names and take the count of wins within each constructor
cons_gb=cons_no1_new.groupby(['name']).count()

In [ ]:
cons_gb.sort_values(by=['wins'],ascending=False)
# cons_gb.merge(constructors_df)

In [ ]:
results_df=pd.read_csv("../data/raw/results.csv")
drivers_df=pd.read_csv("../data/raw/drivers.csv")
drivers_df.drop(columns=['number','url'],inplace=True) # since most of the columns have \n values
drivers_df

In [ ]:
results_drivers_df=results_df.merge(drivers_df,on="driverId",how="inner")

In [ ]:
results_drivers_df.rename(columns={"points":"driver_points"},inplace=True)
results_drivers_df

In [ ]:
constructors_df.rename(columns={'name':'constructor_name','nationality':'constructor_nationality'},inplace=True)
constructors_df

In [ ]:
res_driver_const_df=results_drivers_df.merge(constructors_df,on="constructorId",how="inner")

In [ ]:

res_driver_const_df.rename(columns={'nationality':'driver_nationality',})

In [ ]:
res_driver_const_df.info()

## Races and circuits

In [ ]:
races_df=pd.read_csv("../data/raw/races.csv")
circuits_df=pd.read_csv("../data/raw/circuits.csv")

In [ ]:
races_df.rename(columns={'name':'race_name','url':'races_url'},inplace=True)
circuits_df.rename(columns={'name':'circuit_name','url':'circuits_url'},inplace=True)

In [ ]:
races_circuits_df=races_df.merge(circuits_df,on='circuitId',how="inner")

In [ ]:
races_circuits_df.drop(columns=['alt'],inplace=True)

In [ ]:
races_circuits_df

In [ ]:
# I can see time will be a problem, I will set all the times to seconds for all dataframes with time intervals: 
def hh_mm_ss2seconds(hh_mm_ss):
    return reduce(lambda acc, x: acc*60 + x, map(float, hh_mm_ss.split(':')))

In [ ]:
races_circuits = races_circuits_df.replace({'time': '\\N'}, 0)
races_circuits

In [ ]:

races_circuits.to_csv('../data/Modified/races_circuits.csv', index = False,header=True)

In [ ]:
races_circuits_df1 = pd.read_csv('../data/Modified/races_circuits.csv',
                     converters={'time': hh_mm_ss2seconds})

In [ ]:
races_circuits_df1.to_csv('../data/Modified/races_circuits_final.csv', index = False,header=True)

In [ ]:
races_circuits_df1